#pragma once

#undef PERMISSIVE_HOLD
#undef PERMISSIVE_HOLD_PER_KEY
#undef IGNORE_MOD_TAP_INTERRUPT
#undef IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#undef TAPPING_TERM_PER_KEY
#undef RETRO_TAPPING
#undef RETRO_TAPPING_PER_KEY

#define TAPPING_TERM 157
/* #define PERMISSIVE_HOLD */
/* #define PERMISSIVE_HOLD_PER_KEY */
#define IGNORE_MOD_TAP_INTERRUPT
/* #define IGNORE_MOD_TAP_INTERRUPT_PER_KEY */
#define TAPPING_TERM_PER_KEY
/* #define RETRO_TAPPING */
/* #define RETRO_TAPPING_PER_KEY */
