#pragma once

#undef PERMISSIVE_HOLD
#undef PERMISSIVE_HOLD_PER_KEY
#undef IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#undef TAPPING_TERM_PER_KEY
#undef RETRO_TAPPING
#undef RETRO_TAPPING_PER_KEY

#define TAPPING_TERM 167
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD

#define MOUSEKEY_MOVE_DELTA 2
#define MOUSEKEY_TIME_TO_MAX 240
#define MOUSEKEY_WHEEL_TIME_TO_MAX 240
#define MOUSEKEY_DELAY 40
