#pragma once

#undef PERMISSIVE_HOLD
#undef PERMISSIVE_HOLD_PER_KEY
#undef IGNORE_MOD_TAP_INTERRUPT
#undef IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#undef TAPPING_TERM_PER_KEY
#undef RETRO_TAPPING
#undef RETRO_TAPPING_PER_KEY

#define TAPPING_TERM 167
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

#ifdef RGB_DI_PIN
#define RGBLIGHT_ANIMATIONS
#define RGBLED_NUM 8
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_LIMIT_VAL 100
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_SNAKE
#define RGBLIGHT_DEFAULT_HUE 100
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_SPD 20
#endif

#define MOUSEKEY_MOVE_DELTA 2
#define MOUSEKEY_TIME_TO_MAX 240
#define MOUSEKEY_WHEEL_TIME_TO_MAX 240
#define MOUSEKEY_DELAY 40
