# MCU name
MCU = RP2040

# Board type
BOARD = GENERIC_RP_RP2040

# Bootloader selection
BOOTLOADER = rp2040

# Build Options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
AUDIO_SUPPORTED = no

HAPTIC_ENABLE = yes
HAPTIC_DRIVER += SOLENOID

RGBLIGHT_SUPPORTED = yes
RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = WS2812
WS2812_DRIVER = vendor

LAYOUTS = ortho_3x10
